<p>Створення Обробка та аналіз біомедичних даних</p>

<p>БС-82</p>

<p>Мусієнко</p>

In [2]:
import pandas as pd

In [6]:
new_df=pd.DataFrame(
{
    "Model": ['X', 'XR', 'XS'],
    "ROM": [256, 512, 64],
    "Camera": [12, 16, 16],
    "Color": ['Jet Black', 'Space Grey', 'Gold'],
    "Dual SIM": [False, False, False],
    "Size": [5.8, 6.1, 5.8]
})

new_df

  Model  ROM  Camera       Color  Dual SIM  Size
0     X  256      12   Jet Black     False   5.8
1    XR  512      16  Space Grey     False   6.1
2    XS   64      16        Gold     False   5.8

In [7]:
path="C:/database.csv"
data=pd.read_csv(path, encoding='utf-8')

print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [8]:
import os

print("The directory we are working in is: {}".format(os.getcwd()))

The directory we are working in is: C:\Users\vigor\dasha

In [12]:
data = pd.read_csv('database.csv')

print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [13]:
data

,Flight Number,Launch Date,Launch Time,Launch Site,Vehicle Type,Payload Name,Payload Type,Payload Mass (kg),Payload Orbit,Customer Name,Customer Type,Customer Country,Mission Outcome,Failure Reason,Landing Type,Landing Outcome
0,F1-1,24 March 2006,22:30,Marshall Islands,Falcon 1,FalconSAT-2,Research Satellite,19.5,NaN,DARPA,Government,United States,Failure,Engine Fire During Launch,NaN,NaN
1,F1-2,21 March 2007,01:10,Marshall Islands,Falcon 1,DemoSat,NaN,NaN,NaN,DARPA,Government,United States,Failure,Engine Shutdown During Launch,NaN,NaN
2,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Trailblazer,Communication Satellite,NaN,NaN,ORS,Government,United States,Failure,Collision During Launch,NaN,NaN
3,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,"PRESat, NanoSail-D",Research Satellites,8.0,NaN,NASA,Government,United States,Failure,Collision During Launch,NaN,NaN
4,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Explorers,Human Remains,NaN,NaN,Celestis,Business,United States,Failure,Collision During Launch,NaN,NaN
5,F1-4,28 September 2008,23:15,Marshall Islands,Falcon 1,RatSat (DemoSat),NaN,165.0,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,NaN,NaN
6,F1-5,14 July 2009,03:35,Marshall Islands,Falcon 1,RazakSAT,Weather Satellite,180.0,Low Earth Orbit,ATSB,Government,Malaysia,Success,NaN,NaN,NaN
7,F9-1,4 June 2010,18:45,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),Dragon Spacecraft Qualification Unit,NaN,NaN,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,Parachute,Failure
8,F9-2,8 December 2010,15:43,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C1),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,Parachute,Failure
9,F9-3,22 May 2012,07:44,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C2+),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,NaN,NaN
10,F9-4,8 October 2012,00:35,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS-1,Space Station Supplies,500.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,NaN,NaN
11,F9-4,8 October 2012,00:35,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),Orbcomm-OG2,Communication Satellite,150.0,Low Earth Orbit,Orbcomm,Business,United States,Failure,Engine Failure During Flight,NaN,NaN
12,F9-5,1 March 2013,15:10,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS-2,Space Station Supplies,677.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,NaN,NaN
13,F9-6,29 September 2013,16:00,Vandenberg AFB SLC-4E,Falcon 9 (v1.1),CASSIOPE,Communication/Research Satellite,500.0,Polar Orbit,MDA Corp,Business,Canada,Success,NaN,Ocean,Failure
14,F9-7,3 December 2013,22:41,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SES-8,Communication Satellite,3170.0,Geostationary Transfer Orbit,SES,Business,Luxembourg,Success,NaN,None,NaN
15,F9-8,6 December 2014,22:06,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),Thaicom 6,Communication Satellite,3325.0,Geostationary Transfer Orbit,Thaicom,Business,Thailand,Success,NaN,None,NaN
16,F9-9,18 April 2014,19:25,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SpaceX CRS-3,Space Station Supplies,2296.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Ocean,Success
17,F9-10,14 July 2014,15:15,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),OG2 Mission 1 (6 OG2 Satellites),Communication Satellite,NaN,Low Earth Orbit,Orbcomm,Business,United States,Success,NaN,Ocean,Success
18,F9-11,5 August 2014,08:00,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),AsiaSat 8,Communication Satellite,4535.0,Geostationary Transfer Orbit,AsiaSat,Business,China,Success,NaN,None,NaN
19,F9-12,7 September 2014,05:00,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),AsiaSat 6,Communication Satellite,4428.0,Geostationary Transfer Orbit,AsiaSat,Business,China,Success,NaN,None,NaN
20,F9-13,21 September 2014,05:52,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SpaceX CRS-4,Space Station Supplies,2216.0,Geostationary Transfer Orbit,NASA,Government,United States,Success,NaN,Ocean,Success
21,F9-14,10 January 2015,09:47,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SpaceX CRS-5,Space Station Supplies,2395.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Ship,Failure
22,F9-15,11 February 2015,23:03,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),DSCOVR,Weather Satellite,570.0,Sun/Earth Orbit,US Air Force; NASA; NOAA,Government,United States,Success,NaN,Ocean,Success
23,F9-16,2 March 2015,03:50,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),ABS-3A,Communication Satellite,4159.0,Geostationary Transfer Orbit,Asia Broadcast Satellite,Business,Bermuda,Success,NaN,None,NaN
24,F9-16,2 March 2015,03:50,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),Eutelsat 115 West B (Satmex 7),Communication Satellite,4159.0,Geostationary Transfer Orbit,Eutelsat (Satmex),Business,France (Mexico),Success,NaN,None,NaN
25,F9-17,14 April 2015,20:10,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SpaceX CRS-6,Space Station Supplies,1898.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Ship,Failure
26,F9-18,27 April 2015,23:03,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),TurkmenAlem 52E/MonacoSAT,Communication Satellite,4707.0,Geostationary Transfer Orbit,Turkmenistan NSA,Government,Turkmenistan,Success,NaN,None,NaN
27,F9-19,28 June 2015,14:21,Cape Canaveral AFS LC-40,Falcon 9 (v1.1),SpaceX CRS-7,Space Station Supplies,1952.0,Low Earth Orbit,NASA,Government,United States,Failure,Vehicle Explosion During Flight,NaN,NaN
28,FT-1,22 December 2015,01:29,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),OG2 Mission 2 (11 OG2 Satellites),Communication Satellite,NaN,Low Earth Orbit,Orbcomm,Business,United States,Success,NaN,Land,Success
29,F9-21,17 January 2016,18:42,Vandenberg AFB SLC-4E,Falcon 9 (v1.1),Jason-3,Weather Satellite,553.0,Low Earth Orbit,NASA; NOAA; CNES,Government,United States,Success,NaN,Ship,Failure
30,FT-2,4 March 2016,23:35,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),SES-9,Communication Satellite,5271.0,Geostationary Transfer Orbit,SES,Business,Luxembourg,Success,NaN,Ship,Failure
31,FT-3,8 April 2016,20:43,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),SpaceX CRS-8,Space Station Supplies,3136.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Ship,Success
32,FT-4,6 May 2016,05:21,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),JCSAT-14,Communication Satellite,4696.0,Geostationary Transfer Orbit,SKY Perfect JSAT Group,Business,Japan,Success,NaN,Ship,Success
33,FT-5,27 May 2016,21:39,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),Thaicom 8,Communication Satellite,3100.0,Geostationary Transfer Orbit,Thaicom,Business,Thailand,Success,NaN,Ship,Success
34,FT-6,15 June 2016,14:29,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),ABS-2A,Communication Satellite,3600.0,Geostationary Transfer Orbit,Asia Broadcast Satellite,Business,Bermuda,Success,NaN,Ship,Failure
35,FT-6,15 June 2016,14:29,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),Eutelsat 117 West B (Satmex 9),Communication Satellite,3600.0,Geostationary Transfer Orbit,Eutelsat (Satmex),Business,France (Mexico),Success,NaN,Ship,Failure
36,FT-7,18 July 2016,04:45,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),SpaceX CRS-9,Space Station Supplies,2257.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Land,Success
37,FT-8,14 August 2016,05:26,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),JCSAT-16,Communication Satellite,4600.0,Geostationary Transfer Orbit,SKY Perfect JSAT Group,Business,Japan,Success,NaN,Ship,Success
38,FT-9,1 September 2016,13:07,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),Amos-6,Communication Satellite,5500.0,Geostationary Transfer Orbit,Spacecom,Business,Israel,Failure,Vehicle Explosion Before Launch,NaN,NaN
39,FT-10,14 January 2017,17:54,Vandenberg AFB SLC-4E,Falcon 9 Full Thrust (v1.2),Iridium NEXT 1-10,Communication Satellite,9600.0,Low Earth Orbit,Iridium Communications,Business,United States,Success,NaN,Ship,Success
40,FT-11,19 February 2017,14:39,Kennedy Space Center LC-39A,Falcon 9 Full Thrust (v1.2),SpaceX CRS-10,Space Station Supplies,2490.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Land,Success

In [14]:
data.shape

(41, 16)

In [15]:
data.head(5)

,Flight Number,Launch Date,Launch Time,Launch Site,Vehicle Type,Payload Name,Payload Type,Payload Mass (kg),Payload Orbit,Customer Name,Customer Type,Customer Country,Mission Outcome,Failure Reason,Landing Type,Landing Outcome
0,F1-1,24 March 2006,22:30,Marshall Islands,Falcon 1,FalconSAT-2,Research Satellite,19.5,NaN,DARPA,Government,United States,Failure,Engine Fire During Launch,NaN,NaN
1,F1-2,21 March 2007,01:10,Marshall Islands,Falcon 1,DemoSat,NaN,NaN,NaN,DARPA,Government,United States,Failure,Engine Shutdown During Launch,NaN,NaN
2,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Trailblazer,Communication Satellite,NaN,NaN,ORS,Government,United States,Failure,Collision During Launch,NaN,NaN
3,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,"PRESat, NanoSail-D",Research Satellites,8.0,NaN,NASA,Government,United States,Failure,Collision During Launch,NaN,NaN
4,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Explorers,Human Remains,NaN,NaN,Celestis,Business,United States,Failure,Collision During Launch,NaN,NaN

In [16]:
data.tail(5)

,Flight Number,Launch Date,Launch Time,Launch Site,Vehicle Type,Payload Name,Payload Type,Payload Mass (kg),Payload Orbit,Customer Name,Customer Type,Customer Country,Mission Outcome,Failure Reason,Landing Type,Landing Outcome
36,FT-7,18 July 2016,04:45,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),SpaceX CRS-9,Space Station Supplies,2257.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Land,Success
37,FT-8,14 August 2016,05:26,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),JCSAT-16,Communication Satellite,4600.0,Geostationary Transfer Orbit,SKY Perfect JSAT Group,Business,Japan,Success,NaN,Ship,Success
38,FT-9,1 September 2016,13:07,Cape Canaveral AFS LC-40,Falcon 9 Full Thrust (v1.2),Amos-6,Communication Satellite,5500.0,Geostationary Transfer Orbit,Spacecom,Business,Israel,Failure,Vehicle Explosion Before Launch,NaN,NaN
39,FT-10,14 January 2017,17:54,Vandenberg AFB SLC-4E,Falcon 9 Full Thrust (v1.2),Iridium NEXT 1-10,Communication Satellite,9600.0,Low Earth Orbit,Iridium Communications,Business,United States,Success,NaN,Ship,Success
40,FT-11,19 February 2017,14:39,Kennedy Space Center LC-39A,Falcon 9 Full Thrust (v1.2),SpaceX CRS-10,Space Station Supplies,2490.0,Low Earth Orbit,NASA,Government,United States,Success,NaN,Land,Success

In [21]:
data.dtypes

Flight Number         object
Launch Date           object
Launch Time           object
Launch Site           object
Vehicle Type          object
Payload Name          object
Payload Type          object
Payload Mass (kg)    float64
Payload Orbit         object
Customer Name         object
Customer Type         object
Customer Country      object
Mission Outcome       object
Failure Reason        object
Landing Type          object
Landing Outcome       object
dtype: object

In [19]:
data.describe()

       Payload Mass (kg)
count          33.000000
mean         2739.772727
std          2131.502973
min             8.000000
25%           570.000000
50%          2490.000000
75%          4159.000000
max          9600.000000

In [22]:
data['Payload Type'].describe()

count                          38
unique                          7
top       Communication Satellite
freq                           19
Name: Payload Type, dtype: object

In [23]:
data['Launch Date'].describe()

count                41
unique               36
top       3 August 2008
freq                  3
Name: Launch Date, dtype: object

In [24]:
cut_data=data.iloc[0:10, :]

cut_data

,Flight Number,Launch Date,Launch Time,Launch Site,Vehicle Type,Payload Name,Payload Type,Payload Mass (kg),Payload Orbit,Customer Name,Customer Type,Customer Country,Mission Outcome,Failure Reason,Landing Type,Landing Outcome
0,F1-1,24 March 2006,22:30,Marshall Islands,Falcon 1,FalconSAT-2,Research Satellite,19.5,NaN,DARPA,Government,United States,Failure,Engine Fire During Launch,NaN,NaN
1,F1-2,21 March 2007,01:10,Marshall Islands,Falcon 1,DemoSat,NaN,NaN,NaN,DARPA,Government,United States,Failure,Engine Shutdown During Launch,NaN,NaN
2,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Trailblazer,Communication Satellite,NaN,NaN,ORS,Government,United States,Failure,Collision During Launch,NaN,NaN
3,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,"PRESat, NanoSail-D",Research Satellites,8.0,NaN,NASA,Government,United States,Failure,Collision During Launch,NaN,NaN
4,F1-3,3 August 2008,03:34,Marshall Islands,Falcon 1,Explorers,Human Remains,NaN,NaN,Celestis,Business,United States,Failure,Collision During Launch,NaN,NaN
5,F1-4,28 September 2008,23:15,Marshall Islands,Falcon 1,RatSat (DemoSat),NaN,165.0,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,NaN,NaN
6,F1-5,14 July 2009,03:35,Marshall Islands,Falcon 1,RazakSAT,Weather Satellite,180.0,Low Earth Orbit,ATSB,Government,Malaysia,Success,NaN,NaN,NaN
7,F9-1,4 June 2010,18:45,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),Dragon Spacecraft Qualification Unit,NaN,NaN,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,Parachute,Failure
8,F9-2,8 December 2010,15:43,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C1),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,Parachute,Failure
9,F9-3,22 May 2012,07:44,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C2+),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,NaN,NaN

In [25]:
new_data= ["before 2010", "before 2010", "before 2010", "before 2010", "before 2010", "before 2010", "before 2010", "after 2010", "after 2010", "after 2010" ]
cut_data.insert(1, "Date", new_data)
cut_data

,Flight Number,Date,Launch Date,Launch Time,Launch Site,Vehicle Type,Payload Name,Payload Type,Payload Mass (kg),Payload Orbit,Customer Name,Customer Type,Customer Country,Mission Outcome,Failure Reason,Landing Type,Landing Outcome
0,F1-1,before 2010,24 March 2006,22:30,Marshall Islands,Falcon 1,FalconSAT-2,Research Satellite,19.5,NaN,DARPA,Government,United States,Failure,Engine Fire During Launch,NaN,NaN
1,F1-2,before 2010,21 March 2007,01:10,Marshall Islands,Falcon 1,DemoSat,NaN,NaN,NaN,DARPA,Government,United States,Failure,Engine Shutdown During Launch,NaN,NaN
2,F1-3,before 2010,3 August 2008,03:34,Marshall Islands,Falcon 1,Trailblazer,Communication Satellite,NaN,NaN,ORS,Government,United States,Failure,Collision During Launch,NaN,NaN
3,F1-3,before 2010,3 August 2008,03:34,Marshall Islands,Falcon 1,"PRESat, NanoSail-D",Research Satellites,8.0,NaN,NASA,Government,United States,Failure,Collision During Launch,NaN,NaN
4,F1-3,before 2010,3 August 2008,03:34,Marshall Islands,Falcon 1,Explorers,Human Remains,NaN,NaN,Celestis,Business,United States,Failure,Collision During Launch,NaN,NaN
5,F1-4,before 2010,28 September 2008,23:15,Marshall Islands,Falcon 1,RatSat (DemoSat),NaN,165.0,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,NaN,NaN
6,F1-5,before 2010,14 July 2009,03:35,Marshall Islands,Falcon 1,RazakSAT,Weather Satellite,180.0,Low Earth Orbit,ATSB,Government,Malaysia,Success,NaN,NaN,NaN
7,F9-1,after 2010,4 June 2010,18:45,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),Dragon Spacecraft Qualification Unit,NaN,NaN,Low Earth Orbit,NaN,NaN,NaN,Success,NaN,Parachute,Failure
8,F9-2,after 2010,8 December 2010,15:43,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C1),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,Parachute,Failure
9,F9-3,after 2010,22 May 2012,07:44,Cape Canaveral AFS LC-40,Falcon 9 (v1.0),SpaceX CRS (Dragon C2+),Space Station Supplies,NaN,Low Earth Orbit,NASA,Government,United States,Success,NaN,NaN,NaN

In [26]:
cut_data.groupby('Date').describe()

            Payload Mass (kg)                                                 \
                        count    mean        std  min     25%    50%     75%
Date
after 2010                0.0     NaN        NaN  NaN     NaN    NaN     NaN
before 2010               4.0  93.125  91.978598  8.0  16.625  92.25  168.75


               max
Date
after 2010     NaN
before 2010  180.0

In [27]:
cut_data.to_csv("output.csv", encoding='utf8')